apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-spa
spec:
  selector:
    matchLabels:
      app: live-spa

  template:
    metadata:
      labels:
        app: live-spa
    spec:
      containers:
        - name: live-spa
          image: wesleywillians/maratona2-live-spa:latest
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: live-spa-service
  labels:
    app: live-spa-service
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
  selector:
    app: live-spa

---
  
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: live-spa-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:  
    - "admin.live.fullcycle.com.br"

---
  
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: live-spa-vs
spec:
  hosts:
  - "admin.live.fullcycle.com.br"
  gateways:
  - live-spa-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: live-spa-service  