apiVersion: v1
kind: ConfigMap
metadata:
  name: code-conf
  labels:
    name: code-conf
data:
  env: |
    dbType="postgres"
    dsn="dbname=codebot sslmode=disable user=postgres password=root port=5432 host=codebot-postgres"
    
    dbTypeTest="sqlite3"
    dsnTest=":memory:"
    
    env="dev"
    debug=true
    AutoMigrateDb=true
---
    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codebot
spec:
  selector:
    matchLabels:
      app: codebot

  template:
    metadata:
      labels:
        app: codebot
    spec:
      containers:
        - name: codebot
          image: wesleywillians/maratona2-codebot
          ports:
            - containerPort: 50051
          volumeMounts:
          - name: code-conf
            subPath: .env
            mountPath: /.env

      volumes:
      - name: code-conf
        configMap:
          name: code-conf
          items:
            - key: env
              path: .env

---

apiVersion: v1
kind: Service
metadata:
  name: codebot-service
  labels:
    app: codebot-service
spec:
  type: ClusterIP
  ports:
    - name: grpc
      protocol: TCP
      port: 50051
  selector:
    app: codebot

---

apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: codebot-gateway
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
  - port:
      number: 50051
      name: grpc
      protocol: grpc
    hosts:  
    - "*"
---
  
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: codebot-vs
spec:
  hosts:
  - "*"
  gateways:
  - codebot-gateway
  
  http:
    - match:
      - uri:
          prefix: /
      - port: 50051
      route:
      - destination:
          port:
            number: 50051
          host: codebot-service

  